dist: trusty
language: cpp
matrix:
        include:
                - compiler: gcc
                  env: COMPILER=g++
                - compiler: gcc
                  addons:
                      apt:
                        sources:
                                - ubuntu-toolchain-r-test
                        packages:
                                - libboost-test-dev
                                - libgdk-pixbuf2.0-dev
                                - g++-5
                  env: COMPILER=g++-5
                - compiler: gcc
                  addons:
                      apt:
                        sources:
                                - ubuntu-toolchain-r-test
                        packages:
                                - libboost-test-dev
                                - libgdk-pixbuf2.0-dev
                                - g++-6
                  env: COMPILER=g++-6
                - compiler: clang
                  env: COMPILER=clang++
addons:
        apt:
                packages:
                        - libboost-test-dev
                        - libgdk-pixbuf2.0-dev
script:
        - ./autogen.sh
        - make
        - make check